name: Setup Script with Interactive Inputs

on:
  workflow_dispatch:
    inputs:
      ssh_user:
        description: 'SSH username for nodes'
        required: true
        default: 'user'
      node_ips:
        description: 'Space-separated IP addresses or hostnames of nodes (e.g. "192.168.1.10 server2")'
        required: true
        default: '192.168.1.10'
      snmp_ips:
        description: 'Space-separated SNMP device addresses (e.g. "10.0.0.1 10.0.0.2")'
        required: true
        default: '10.0.0.1'
      snmp_user:
        description: 'SNMP device user'
        required: true
        default: 'public'
      snmp_pass:
        description: 'SNMP device password'
        required: true
        default: 'public'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update variables at the top of setup.sh
        run: |
          # Backup file
          cp setup.sh setup.sh.bak

          # Prepare replacements
          SSH_USER_VAL="${{ github.event.inputs.ssh_user }}"
          SNMPUSER_VAL="${{ github.event.inputs.snmp_user }}"
          SNMPASS_VAL="${{ github.event.inputs.snmp_pass }}"

          # Convert space-separated strings into bash arrays syntax
          IFS=' ' read -r -a NODE_IPS_ARRAY <<< "${{ github.event.inputs.node_ips }}"
          IFS=' ' read -r -a SNMPIPS_ARRAY <<< "${{ github.event.inputs.snmp_ips }}"

          NODE_IPS_VAL="NODE_IPS=(${NODE_IPS_ARRAY[@]})"
          SNMPIPS_VAL="SNMPIPS=(${SNMPIPS_ARRAY[@]})"

          # Use sed to replace or insert these lines near the top of the file (after any shebang)
          # Function to insert or replace variable near the top
          replace_or_insert() {
            local var_name=$1
            local var_val=$2
            local file=$3

            if grep -q "^$var_name=" "$file"; then
              # Replace existing line
              sed -i "0,/^$var_name=/s/^$var_name=.*/$var_val/" "$file"
            else
              # Insert after shebang or at start
              if head -1 "$file" | grep -q "^#!"; then
                sed -i "1a $var_val" "$file"
              else
                sed -i "1i $var_val" "$file"
              fi
            fi
          }

          replace_or_insert "SSH_USER" "SSH_USER='$SSH_USER_VAL'" setup.sh
          replace_or_insert "NODE_IPS" "$NODE_IPS_VAL" setup.sh
          replace_or_insert "SNMPIPS" "$SNMPIPS_VAL" setup.sh
          replace_or_insert "SNMPUSER" "SNMPUSER='$SNMPUSER_VAL'" setup.sh
          replace_or_insert "SNMPASS" "SNMPASS='$SNMPASS_VAL'" setup.sh

      - name: Show updated setup.sh
        run: cat setup.sh

      - name: Make changes to a file
        run: |
          echo "This is a new line" >> test

      - name: Configure Git
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"

      - name: Commit changes
        run: |
          git add test
          git commit -m "Update test with a new line" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main
