name: Скрипт с указанием переменных

on:
  workflow_dispatch:
    inputs:
      ssh_user:
        description: 'SSH username для рабочих станций'
        required: true
        default: 'user'
      node_ips:
        description: 'Разделенные пробелом IP или доменные имена раб.станций (e.g. "192.168.1.10 server2")'
        required: true
        default: '192.168.1.10'
      snmp_ips:
        description: 'Разделенные пробелом IP или доменные имена SNMP устройств (e.g. "10.0.0.1 router2")'
        required: true
        default: '10.0.0.1'
      snmp_user:
        description: 'SNMP user'
        required: true
        default: 'public'
      snmp_pass:
        description: 'SNMP password'
        required: true
        default: 'public'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update variables in setup.sh
        run: |
          cp setup.sh setup.sh.bak

          SSH_USER_VAL="${{ github.event.inputs.ssh_user }}"
          SNMPUSER_VAL="${{ github.event.inputs.snmp_user }}"
          SNMPASS_VAL="${{ github.event.inputs.snmp_pass }}"

          IFS=' ' read -r -a NODE_IPS_ARRAY <<< "${{ github.event.inputs.node_ips }}"
          IFS=' ' read -r -a SNMPIPS_ARRAY <<< "${{ github.event.inputs.snmp_ips }}"

          NODE_IPS_VAL="NODE_IPS=(${NODE_IPS_ARRAY[@]})"
          SNMPIPS_VAL="SNMPIPS=(${SNMPIPS_ARRAY[@]})"

          replace_or_insert() {
            local var_name=$1
            local var_val=$2
            local file=$3

            if grep -q "^$var_name=" "$file"; then
              # Replace existing line
              sed -i "0,/^$var_name=/s/^$var_name=.*/$var_val/" "$file"
            else
              if head -1 "$file" | grep -q "^#!"; then
                sed -i "1a $var_val" "$file"
              else
                sed -i "1i $var_val" "$file"
              fi
            fi
          }

          replace_or_insert "SSH_USER" "SSH_USER='$SSH_USER_VAL'" setup.sh
          replace_or_insert "NODE_IPS" "$NODE_IPS_VAL" setup.sh
          replace_or_insert "SNMPIPS" "$SNMPIPS_VAL" setup.sh
          replace_or_insert "SNMPUSER" "SNMPUSER='$SNMPUSER_VAL'" setup.sh
          replace_or_insert "SNMPASS" "SNMPASS='$SNMPASS_VAL'" setup.sh

      - name: Show updated setup.sh
        run: cat setup.sh

      - name: Configure Git
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"

      - name: Commit changes
        run: |
          git add setup.sh
          git commit -m "Update setup.sh" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main
